FROM golang:1.20.6-alpine3.18

WORKDIR /todo-app/backend
COPY ./backend .

# RUN ls /todo-app/backend

RUN apk upgrade --update && apk --no-cache add git

RUN go install github.com/cosmtrek/air@latest

CMD ["air", "-c", "air.toml"]